paths:
  data_root: data
  ball_dataset: data/datasets/balltracking
  court_dataset: data/datasets/court_identification
  checkpoints_root: checkpoints
  outputs_root: outputs

models:
  ball:
    input_height: 360
    input_width: 640
    out_channels: 256
  court:
    input_height: 720
    input_width: 1280
    scale: 2
    out_channels: 15

runtime:
  device: auto
